### ISSUE TITLE
Change var -> const/let

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/Melting-Chocolate-Simulation#2]
### Description

Change instances of "var" to "const" or "let". This will improve the code quality.

**Operating System:** n/a

**Browser:** n/a

### Steps to Reproduce

n/a

**Expected behavior:** n/a

**Actual behavior:** n/a

### Additional Information

n/a

**Comment by geoffreykwan** [comment]
Completed
https://github.com/WISE-Community/Thermodynamics-Melting-Chocolate-Simulation/commit/7544bb0661c34af586b31611572a9965179fcc4c
